version: '3.8'

services:
  ocr_service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - symbiota-network

networks:
  symbiota-network:
    external: true